### ISSUE TITLE
template stacks unable to start with templating-controller v0.3.0-rc

### ISSUE THREAD

**Issue by jbw976** [crossplane/templating-controller#13]
The latest template stacks look to be broken after upgrading them to `templating-controller:v0.3.0-rc`.  They are in a crashloop backoff with:

```
starting container: starting non-root container [/manager --resources-dir /behaviors --stack-definition-namespace crossplane-system --stack-definition-name crossplane-stack-minimal-gcpv0.4.0-rc-2-g0200e9a]: creating process: Failed to load /manager: no such file or directory
```

Perhaps the entry point of `/manager` changed in the latest templating-controller so hopefully it's an easy fix to point the deployments that the stackmanager generates to a new entry point.

**Comment by jbw976** [comment]
With the migration to using the build submodule, the binary name inside the container and the entry point are now `templating-controller`:
https://github.com/crossplane/templating-controller/blob/master/cluster/images/templating-controller/Dockerfile#L9

We'll need to adjust the stack manager accordingly here:
https://github.com/crossplane/crossplane/blob/master/pkg/stacks/unpack.go#L292

**Comment by displague** [comment]
@jbw976 Do you suppose the stack-manager should base the binary name on `sd.Engine.ControllerImage` rather than having a hard-coded name?

We could permit `app.yaml` to override the entry-point.

Another option would be to expect the the entry-point to be set by the container and then invoke the arguments using `CMD`.

**Comment by suskin** [comment]
> Another option would be to expect the the entry-point to be set by the container and then invoke the arguments using CMD

+1 for this option. The most backwards-compatible approach seems like it'd be:

1. Change templating-controller to use `/manager` again
2. Change the stack manager to use the container's entrypoint
3. Change templating-controller back to `/templating-controller`

**Comment by muvaf** [comment]
Actually, if we just removed [`Command`](https://github.com/crossplane/crossplane/blob/master/pkg/stacks/unpack.go#L292) from the controller spec, it should pick up templating-controller's default `ENTRYPOINT` [command](https://github.com/crossplane/templating-controller/blob/master/cluster/images/templating-controller/Dockerfile#L9). I didn't test this but [doc says so](https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#define-a-command-and-arguments-when-you-create-a-pod).

EDIT: I just got two comments above when I sent my comment, bad effect of keeping browser tabs open too long :(

**Comment by muvaf** [comment]
> Another option would be to expect the the entry-point to be set by the container and then invoke the arguments using CMD.

I think `ENTRYPOINT` is the one that we'd append the `args`, see [Notes](https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#notes) section in doc for equivalence table.

**Comment by jbw976** [comment]
From that link @muvaf, it seems like this is what we would want:

> If you supply only args for a Container, the default Entrypoint defined in the Docker image is run with the args that you supplied.

Both v0.2.1 and v0.3.0-rc of templating-controller define the Entrypoint explicitly:
* https://github.com/crossplane/templating-controller/blob/bddbed4259a6b088bb6e37452db03a175b89f02b/cluster/images/templating-controller/Dockerfile#L9
* https://github.com/crossplane/templating-controller/blob/a035e2a7970eef89d76196f702bb7c3916f95e45/Dockerfile#L17

I'm hoping they expect the same arguments as well, which they seem to:
* https://github.com/crossplane/templating-controller/blob/bddbed4259a6b088bb6e37452db03a175b89f02b/cmd/templating-controller/main.go#L61-L64
* https://github.com/crossplane/templating-controller/blob/a035e2a7970eef89d76196f702bb7c3916f95e45/main.go#L61-L64

**Comment by jbw976** [comment]
Re-opening to validate the changes after they are published
